<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JS_errors</title>
    <style>
        code {
            color: tomato;
            font-size: x-large;
            font-weight: bold;
            border: solid 1px tomato;
            padding: 3px;
        }
    </style>
</head>
<body>
    <h1>例外処理</h1>
    <ul>
        <li>try・・・試行するコードブロックを定義する。</li>
        <li>catch・・・エラーを処理するコードブロックを定義する。</li>
        <li>finally・・・結果に関係なく実行するコードブロックを定義する。</li>
        <li>throw・・・カスタムエラーを定義する。</li>
    </ul>

    <h2>エラーは起こるもの！</h2>
    <p id="demo1"></p>
    <hr>
    <h2>try&catch</h2>
    <p><code>try</code> を使用すると、実行中にエラーをテストコードブロックを定義できる。</p>
    <p><code>catch</code> を使用すると、<code>try</code> エラーが発生した場合に実行されるコードのブロックを定義できる。
    </p>
    <p>エラーが発生すると、
        通常は停止し、エラーメッセージが生成される。
    </p>
    <p>専門用語だと、「例外をスローする。」</p>

    <p>5から10までの数値を入力してください。</p>
    <input type="demo2" type="text">
    <button type="button" onclick="myFunction()">値を入力</button>
    <p id="p01"></p>

    <script>
        try {
            adddlert("Welcom quest!");
        }
        catch(err){
            document.getElementById("demo1").innerHTML = 
            err.message + "<br>↑<br>構文のalertがadddertと間違っている事を表示している。";
        }

        function myFunction(){
            const message = document.getElementById("p01");
            message.innerHTML = "";
            let x = document.getElementById("demo2").value;
            try {
                if(x.trim() == "") throw "empty";
                if(isNaN(x)) throw "not a number";
                x = Number(x);
                if(x < 5) throw "too low";
                if(x > 10) throw "too high";
            }
            catch(err){
                message.innerHTML = "Input is " + err;
            }
        }
    </script>

</body>
</html>